2025-09-01 20:41:39,208 [ERROR] 未捕捉的例外: unknown opcode
Traceback (most recent call last):
  File "C:\Users\User\Desktop\project\2.PI-DX\main.py", line 46, in <module>
    main()
  File "C:\Users\User\Desktop\project\2.PI-DX\main.py", line 42, in main
    App(cfg, notes=[]).run()
  File "C:\Users\User\Desktop\project\2.PI-DX\app.py", line 297, in run
    self.renderer.draw_notes(self.notes_sorted, self.note_starts, self.time)
  File "C:\Users\User\Desktop\project\2.PI-DX\render\renderer.py", line 160, in draw_notes
    x, w, is_black = self.pitch_to_xw(n.pitch)
  File "C:\Users\User\Desktop\project\2.PI-DX\render\renderer.py", line 127, in pitch_to_xw
    white_w = self.cfg.window_w / max(1, total_white)
SystemError: unknown opcode
